apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "django-app.fullname" . }}
  namespace: {{ .Release.Namespace }}  # Использовать Release.Namespace вместо Values.global.namespace
  labels:
    {{- include "django-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      {{- include "django-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "django-app.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.app.port }}"
        prometheus.io/path: "/metrics"
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "localhost:5001/django-app:latest"
          #image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.app.port }}
          env:
            - name: DB_HOST
              value: {{ .Release.Name }}-postgresql
            - name: DB_NAME
              value: {{ .Values.postgresql.auth.database | quote }}
            - name: DB_USER
              value: {{ .Values.postgresql.auth.username | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgresql
                  key: password
            - name: DEBUG
              value: {{ .Values.env.DEBUG | quote }}
            - name: ALLOWED_HOSTS
              value: {{ .Values.env.ALLOWED_HOSTS | quote }}
          livenessProbe:
            httpGet:
              path: /health/
              port: {{ .Values.app.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/
              port: {{ .Values.app.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}